### PR TITLE
Soften removal of investor_name and portfolio_name

### LINKED ISSUE #7: `pacta.portfolio.audit::get_input_files()` can't subset what doesn't exist
Reprex steps: 
- Run a portfolio with NO `investor_name` or `portfolio_name` as input to PACTA

Error:
Screenshot 2023-05-04 at 9 21 21 PM

### PR DESCRIPTION
**Pull request by jdhoffa**
Input portfolios may or may not have the columns `investor_name` and `portfolio_name`. 
This PR adjusts the function `get_input_files` to first check if they do, and then IF they do tries to remove them, otherwise, it does nothing. 

Closes #7

### CODE REVIEW

**Comment by jdhoffa** [comment]
Also.... I don't really understand how this didn't cause bugs before?

File: R/get_input_files.R [hunk 1]
```diff
@@ -71,7 +71,8 @@ get_input_files <- function(portfolio_name_ref_all) {
   input_file_path <- path(input_path, paste0(portfolio_name_ref_all, ".csv"))
 
   portfolio <- pacta.portfolio.import::read_portfolio_csv(input_file_path)
-  portfolio <- portfolio %>% select(-"investor_name", -"portfolio_name")
+  portfolio <- portfolio %>%
+    select(-dplyr::starts_with(c("investor_name", "portfolio_name")))
```
Comment (cjyetman) [inline R/get_input_files.R:75]:
```suggestion
    select(-dplyr::any_of(c("investor_name", "portfolio_name")))
```
I'd rather use `dplyr::any_of()` here... it's more to the point.

Comment (jdhoffa) [reply R/get_input_files.R:75]: Happy with that!

**Review by cjyetman — APPROVED** [review]
